version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: comprinhas_postgres
    restart: always
    environment:
      POSTGRES_USER: comprinhas_user
      POSTGRES_PASSWORD: comprinhas_pass
      POSTGRES_DB: comprinhas_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: